import type { DailyRecord, MonthlyRecord } from "@/lib/attendance-types";

export const MOCK_DAILY: DailyRecord[] = [
  {
    id: "1",
    employeeId: "emp-1",
    name: "Sarah Jenkins",
    role: "Senior Developer",
    status: "present",
    location: "New York HQ",
    loginTime: "08:45 AM",
    logoutTime: undefined,
    totalHours: "3h 15m",
  },
  {
    id: "2",
    employeeId: "emp-2",
    name: "Marcus Chen",
    role: "Product Lead",
    status: "present",
    location: "Seattle (Home)",
    loginTime: "09:02 AM",
    logoutTime: undefined,
    totalHours: "2h 58m",
  },
  {
    id: "3",
    employeeId: "emp-3",
    name: "Elena Rodriguez",
    role: "Data Analyst",
    status: "late",
    location: "Austin Office",
    loginTime: "09:47 AM",
    logoutTime: undefined,
    totalHours: "2h 13m",
  },
  {
    id: "4",
    employeeId: "emp-4",
    name: "David Kim",
    role: "HR Specialist",
    status: "on leave",
    location: "PTO (Annual)",
    loginTime: undefined,
    logoutTime: undefined,
    totalHours: undefined,
  },
  {
    id: "5",
    employeeId: "emp-5",
    name: "Chloe Vance",
    role: "Marketing Lead",
    status: "checked out",
    location: "London Hub",
    loginTime: "07:38 AM",
    logoutTime: "11:45 AM",
    totalHours: "4h 15m",
  },
  {
    id: "6",
    employeeId: "emp-6",
    name: "James Okafor",
    role: "Backend Engineer",
    status: "present",
    location: "New York HQ",
    loginTime: "08:30 AM",
    logoutTime: undefined,
    totalHours: "3h 30m",
  },
  {
    id: "7",
    employeeId: "emp-7",
    name: "Priya Sharma",
    role: "UX Designer",
    status: "half day",
    location: "Bengaluru Office",
    loginTime: "09:00 AM",
    logoutTime: "01:00 PM",
    totalHours: "4h 00m",
  },
];

export const MOCK_MONTHLY: MonthlyRecord[] = [
  {
    id: "1",
    employeeId: "emp-1",
    name: "Sarah Jenkins",
    role: "Senior Engineer",
    attendanceRate: 95,
    totalPresent: 20,
    totalLate: 1,
    totalLeaves: 1,
    monthlyStatus: "on track",
  },
  {
    id: "2",
    employeeId: "emp-2",
    name: "Marcus Chen",
    role: "Product Manager",
    attendanceRate: 88,
    totalPresent: 18,
    totalLate: 2,
    totalLeaves: 2,
    monthlyStatus: "on track",
  },
  {
    id: "3",
    employeeId: "emp-3",
    name: "Elena Rodriguez",
    role: "UX Designer",
    attendanceRate: 75,
    totalPresent: 15,
    totalLate: 4,
    totalLeaves: 3,
    monthlyStatus: "warning",
  },
  {
    id: "4",
    employeeId: "emp-4",
    name: "David Kim",
    role: "Data Analyst",
    attendanceRate: 100,
    totalPresent: 22,
    totalLate: 0,
    totalLeaves: 0,
    monthlyStatus: "on track",
  },
  {
    id: "5",
    employeeId: "emp-5",
    name: "Chloe Vance",
    role: "Marketing Specialist",
    attendanceRate: 90,
    totalPresent: 19,
    totalLate: 1,
    totalLeaves: 2,
    monthlyStatus: "on track",
  },
  {
    id: "6",
    employeeId: "emp-6",
    name: "James Okafor",
    role: "Backend Engineer",
    attendanceRate: 60,
    totalPresent: 12,
    totalLate: 5,
    totalLeaves: 6,
    monthlyStatus: "critical",
  },
];