'use client'

import {
  type MockSprint,
  TrackSprintGroup,
} from '@/components/tracks/track-sprint-group'
import { Id } from '@/convex/_generated/dataModel'

const mockSprints: MockSprint[] = [
  {
    id: 'sprint-1',
    number: 1,
    goal: 'Finalize planning workflow and baseline board visibility',
    startDate: new Date('2026-06-01').getTime(),
    endDate: new Date('2026-06-14').getTime(),
    tasks: [
      {
        _id: '1' as Id<'tasks'>,
        title: 'Add sprint header with goal and progress indicators',
        status: 'done',
        createdAt: new Date('2026-06-01').getTime(),
        updatedAt: new Date('2026-06-01').getTime(),
        sprintId: 'sprint-1' as Id<'sprints'>,
        trackId: 'track-1' as Id<'tracks'>,
        projectId: 'project-1' as Id<'projects'>,
        taskCode: '1',
        description: 'Add sprint header with goal and progress indicators',
        priority: 'medium',
        complexity: 'medium',
        startedAt: new Date('2026-06-01').getTime(),
        dueDate: new Date('2026-06-14').getTime(),
        completedAt: new Date('2026-06-14').getTime(),
        _creationTime: new Date().getTime(),
        createdBy: 'user-1' as MockSprint['tasks'][number]['createdBy'],
      },
      {
        _id: '2' as Id<'tasks'>,
        title: 'Implement sprint date range editing in group header',
        status: 'done',
        createdAt: new Date('2026-06-01').getTime(),
        updatedAt: new Date('2026-06-01').getTime(),
        sprintId: 'sprint-1' as Id<'sprints'>,
        trackId: 'track-1' as Id<'tracks'>,
        projectId: 'project-1' as Id<'projects'>,
        taskCode: '2',
        description: 'Implement sprint date range editing in group header',
        priority: 'medium',
        complexity: 'medium',
        startedAt: new Date('2026-06-01').getTime(),
        dueDate: new Date('2026-06-14').getTime(),
        completedAt: new Date('2026-06-14').getTime(),
        _creationTime: new Date().getTime(),
        createdBy: 'user-1' as MockSprint['tasks'][number]['createdBy'],
      },
      {
        _id: '3' as Id<'tasks'>,
        title: 'Enable add issue shortcut from sprint lane',
        status: 'todo',
        createdAt: new Date('2026-06-01').getTime(),
        updatedAt: new Date('2026-06-01').getTime(),
        sprintId: 'sprint-1' as Id<'sprints'>,
        trackId: 'track-1' as Id<'tracks'>,
        projectId: 'project-1' as Id<'projects'>,
        taskCode: '3',
        description: 'Enable add issue shortcut from sprint lane',
        priority: 'medium',
        complexity: 'medium',
        startedAt: new Date('2026-06-01').getTime(),
        dueDate: new Date('2026-06-14').getTime(),
        completedAt: new Date('2026-06-14').getTime(),
        _creationTime: new Date().getTime(),
        createdBy: 'user-1' as MockSprint['tasks'][number]['createdBy'],
      },
    ],
  },
  {
    id: 'sprint-2',
    number: 2,
    goal: 'Improve team execution with assignment and status hygiene',
    startDate: new Date('2026-06-15').getTime(),
    endDate: new Date('2026-06-28').getTime(),
    tasks: [
      {
        _id: 'sp2-task-1' as Id<'tasks'>,
        title: 'Review all carry-over tasks and re-estimate effort',
        status: 'done',
        createdAt: new Date('2026-06-01').getTime(),
        updatedAt: new Date('2026-06-01').getTime(),
        sprintId: 'sprint-2' as Id<'sprints'>,
        trackId: 'track-2' as Id<'tracks'>,
        projectId: 'project-2' as Id<'projects'>,
        taskCode: '1',
        description: 'Review all carry-over tasks and re-estimate effort',
        priority: 'medium',
        complexity: 'medium',
        startedAt: new Date('2026-06-01').getTime(),
        dueDate: new Date('2026-06-14').getTime(),
        completedAt: new Date('2026-06-14').getTime(),
        _creationTime: new Date().getTime(),
        createdBy: 'user-1' as MockSprint['tasks'][number]['createdBy'],
      },
      {
        _id: '2' as Id<'tasks'>,
        title: 'Assign owners for remaining pending tasks',
        status: 'in_progress',
        createdAt: new Date('2026-06-01').getTime(),
        updatedAt: new Date('2026-06-01').getTime(),
        sprintId: 'sprint-2' as Id<'sprints'>,
        trackId: 'track-2' as Id<'tracks'>,
        projectId: 'project-2' as Id<'projects'>,
        taskCode: '2',
        description: 'Assign owners for remaining pending tasks',
        priority: 'medium',
        complexity: 'medium',
        startedAt: new Date('2026-06-01').getTime(),
        dueDate: new Date('2026-06-14').getTime(),
        completedAt: new Date('2026-06-14').getTime(),
        _creationTime: new Date().getTime(),
        createdBy: 'user-1' as MockSprint['tasks'][number]['createdBy'],
      },
      {
        _id: 'sp2-task-3' as Id<'tasks'>,
        title: 'Add blocked reason labels for unresolved work',
        status: 'in_progress',
        createdAt: new Date('2026-06-01').getTime(),
        updatedAt: new Date('2026-06-01').getTime(),
        sprintId: 'sprint-2' as Id<'sprints'>,
        trackId: 'track-2' as Id<'tracks'>,
        projectId: 'project-2' as Id<'projects'>,
        taskCode: '3',
        description: 'Add blocked reason labels for unresolved work',
        priority: 'medium',
        complexity: 'medium',
        startedAt: new Date('2026-06-01').getTime(),
        dueDate: new Date('2026-06-14').getTime(),
        completedAt: new Date('2026-06-14').getTime(),
        _creationTime: new Date().getTime(),
        createdBy: 'user-1' as MockSprint['tasks'][number]['createdBy'],
      },
      {
        _id: '4' as Id<'tasks'>,
        title: 'Create sprint review note template',
        status: 'todo',
        createdAt: new Date('2026-06-01').getTime(),
        updatedAt: new Date('2026-06-01').getTime(),
        sprintId: 'sprint-2' as Id<'sprints'>,
        trackId: 'track-2' as Id<'tracks'>,
        projectId: 'project-2' as Id<'projects'>,
        taskCode: '4',
        description: 'Create sprint review note template',
        priority: 'medium',
        complexity: 'medium',
        startedAt: new Date('2026-06-01').getTime(),
        dueDate: new Date('2026-06-14').getTime(),
        completedAt: new Date('2026-06-14').getTime(),
        _creationTime: new Date().getTime(),
        createdBy: 'user-1' as MockSprint['tasks'][number]['createdBy'],
      },
    ],
  },
  {
    id: 'sprint-3',
    number: 3,
    goal: 'Prepare release candidate and stabilize task completion',
    startDate: new Date('2026-06-29').getTime(),
    endDate: new Date('2026-07-12').getTime(),
    tasks: [
      {
        _id: '1' as Id<'tasks'>,
        title: 'Run QA sweep on completed stories',
        status: 'done',
        createdAt: new Date('2026-06-01').getTime(),
        updatedAt: new Date('2026-06-01').getTime(),
        sprintId: 'sprint-3' as Id<'sprints'>,
        trackId: 'track-3' as Id<'tracks'>,
        projectId: 'project-3' as Id<'projects'>,
        taskCode: '1',
        description: 'Run QA sweep on completed stories',
        priority: 'medium',
        complexity: 'medium',
        startedAt: new Date('2026-06-01').getTime(),
        dueDate: new Date('2026-06-14').getTime(),
        completedAt: new Date('2026-06-14').getTime(),
        _creationTime: new Date().getTime(),
        createdBy: 'user-1' as MockSprint['tasks'][number]['createdBy'],
      },
      {
        _id: '2' as Id<'tasks'>,
        title: 'Close stale tasks with no activity in 14 days',
        status: 'done',
        createdAt: new Date('2026-06-01').getTime(),
        updatedAt: new Date('2026-06-01').getTime(),
        sprintId: 'sprint-3' as Id<'sprints'>,
        trackId: 'track-3' as Id<'tracks'>,
        projectId: 'project-3' as Id<'projects'>,
        taskCode: '2',
        description: 'Close stale tasks with no activity in 14 days',
        priority: 'medium',
        complexity: 'medium',
        startedAt: new Date('2026-06-01').getTime(),
        dueDate: new Date('2026-06-14').getTime(),
        completedAt: new Date('2026-06-14').getTime(),
        _creationTime: new Date().getTime(),
        createdBy: 'user-1' as MockSprint['tasks'][number]['createdBy'],
      },
      {
        _id: '3' as Id<'tasks'>,
        title: 'Finalize release checklist and owner sign-off',
        status: 'todo',
        createdAt: new Date('2026-06-01').getTime(),
        updatedAt: new Date('2026-06-01').getTime(),
        sprintId: 'sprint-3' as Id<'sprints'>,
        trackId: 'track-3' as Id<'tracks'>,
        projectId: 'project-3' as Id<'projects'>,
        taskCode: '3',
        description: 'Finalize release checklist and owner sign-off',
        priority: 'medium',
        complexity: 'medium',
        startedAt: new Date('2026-06-01').getTime(),
        dueDate: new Date('2026-06-14').getTime(),
        completedAt: new Date('2026-06-14').getTime(),
        _creationTime: new Date().getTime(),
        createdBy: 'user-1' as MockSprint['tasks'][number]['createdBy'],
      },
      {
        _id: 'sp3-task-4' as Id<'tasks'>,
        title: 'Publish sprint retrospective notes to project wiki',
        status: 'in_progress',
        createdAt: new Date('2026-06-01').getTime(),
        updatedAt: new Date('2026-06-01').getTime(),
        sprintId: 'sprint-3' as Id<'sprints'>,
        trackId: 'track-3' as Id<'tracks'>,
        projectId: 'project-3' as Id<'projects'>,
        taskCode: '4',
        description: 'Publish sprint retrospective notes to project wiki',
        priority: 'medium',
        complexity: 'medium',
        startedAt: new Date('2026-06-01').getTime(),
        dueDate: new Date('2026-06-14').getTime(),
        completedAt: new Date('2026-06-14').getTime(),
        _creationTime: new Date().getTime(),
        createdBy: 'user-1' as MockSprint['tasks'][number]['createdBy'],
      },
    ],
  },
]

export function TrackSprintsView() {
  return (
    <div className="min-h-0 flex-1">
      {mockSprints.map((sprint) => (
        <TrackSprintGroup key={sprint.id} sprint={sprint} />
      ))}
    </div>
  )
}
